In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("processed_insurance.csv")

df.head()

,age,sex,bmi,children,smoker,region,charges,insuranceclaim,BMI_Age,Family_Size
0,19,0,27.900,0,1,3,16884.92400,1,530.100,1
1,18,1,33.770,1,0,2,1725.55230,1,607.860,2
2,28,1,33.000,3,0,2,4449.46200,0,924.000,4
3,33,1,22.705,0,0,1,21984.47061,0,749.265,1
4,32,1,28.880,0,0,1,3866.85520,1,924.160,1

In [3]:
X = df.drop("insuranceclaim", axis=1)

y = df["insuranceclaim"]

In [4]:
print(X.shape)
print(y.shape)

(1338, 9)
(1338,)

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [6]:
print("Training:", X_train.shape)
print("Testing:", X_test.shape)

Training: (1070, 9)
Testing: (268, 9)

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

pred_lr = lr.predict(X_test)

acc_lr = accuracy_score(
    y_test,
    pred_lr
)

print("Logistic Regression Accuracy:", acc_lr)

Logistic Regression Accuracy: 0.8656716417910447

In [10]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    random_state=42
)

rf.fit(X_train, y_train)

pred_rf = rf.predict(X_test)

acc_rf = accuracy_score(
    y_test,
    pred_rf
)

print("Random Forest Accuracy:", acc_rf)

Random Forest Accuracy: 0.9477611940298507

In [11]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(
    random_state=42
)

gb.fit(X_train, y_train)

pred_gb = gb.predict(X_test)

acc_gb = accuracy_score(
    y_test,
    pred_gb
)

print("Gradient Boosting Accuracy:", acc_gb)

Gradient Boosting Accuracy: 0.9589552238805971

In [12]:
results = pd.DataFrame({
    "Model":[
        "Logistic Regression",
        "Random Forest",
        "Gradient Boosting"
    ],
    "Accuracy":[
        acc_lr,
        acc_rf,
        acc_gb
    ]
})

results

                 Model  Accuracy
0  Logistic Regression  0.865672
1        Random Forest  0.947761
2    Gradient Boosting  0.958955

In [13]:
print(results.sort_values(
    by="Accuracy",
    ascending=False
))

                 Model  Accuracy
2    Gradient Boosting  0.958955
1        Random Forest  0.947761
0  Logistic Regression  0.865672